---
abstract: 'Perl Regular expressions made easy'
author:
  - 'Takumi Akiyama <t.akiym@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.5.6, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Regexp-VerbalExpressions
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Regexp::VerbalExpressions:
    file: lib/Regexp/VerbalExpressions.pm
    version: 0.01
requires:
  perl: 5.008005
resources:
  bugtracker: https://github.com/VerbalExpressions/PerlVerbalExpressions/issues
  homepage: https://github.com/VerbalExpressions/PerlVerbalExpressions
  repository: git://github.com/VerbalExpressions/PerlVerbalExpressions.git
version: 0.01
